name: laminas-chatgpt
recipe: lamp
config:
  webroot: public
  php: 8.1
  xdebug: true
  conf:
    php: .lando/php.ini

proxy:
  appserver:
    - laminas-chatgpt.lndo.site/
  pma:
    - pma.laminas-chatgpt.lndo.site/
 # database: