<h1><?= $this->form->get('id')->getValue() ? 'Edit User' : 'Add User' ?></h1>

<div class="container">
    <form method="post" action="/user/add">
        <?= $this->form()->openTag($form) ?>

        <div class="row">
            <div class="col-6">
                <?= $this->formRow($form->get('name')) ?>
            </div>
            <div class="col-6">
                <?= $this->formRow($form->get('email')) ?>
            </div>

        </div>

        <div class="row mt-2">
            <div class="col-6">
                <?= $this->formRow($form->get('password')) ?>
            </div>
            <div class="d-flex justify-content-end">
                <?= $this->formSubmit($form->get('submit')) ?>
                <?= $this->form()->closeTag() ?>
            </div>
        </div>
    </form>
</div>